/* IN THIS PROJET WE ARE GOING TO USED 80 PERCENT SQL AND 20 PERCENT POWER BI
CUSTOMER SEGMENTATION USING RFM. DATASET CONTAINS 2823 RECORDS FROM KAGGLE */ 

SELECT * FROM sales_table;

SELECT count(*)
FROM sales_table WHERE ORDERNUMBER IS NULL AND ORDERNUMBER = '';

SELECT COUNT(*)
FROM sales_table; -- 2823 RECORDS 

SELECT MIN(ORDERDATE), MAX(ORDERDATE) FROM sales_table; -- 2003 TO 2005( APRIL)

-- ********************** EXPLORING DATA ****************************************
-- UNIQUE VALUES 

SELECT DISTINCT STATUS FROM sales_table ;
SELECT DISTINCT PRODUCTLINE FROM sales_table ;
SELECT DISTINCT COUNTRY FROM sales_table ;
SELECT DISTINCT TERRITORY FROM sales_table ;
SELECT DISTINCT DEALSIZE FROM sales_table ;
SELECT DISTINCT YEAR_ID FROM sales_table ;


-- BUSINESS QUESTION TO EXPLORE
-- 1. SALES BY PRODUCTLINE
SELECT PRODUCTLINE,ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
GROUP BY PRODUCTLINE
ORDER BY 2 DESC;

-- 2. THE SALES AMOUNT BY YEARS
SELECT YEAR_ID,ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
GROUP BY YEAR_ID
ORDER BY 2 DESC;
 
-- WHY 2005 AS THE LOWEST SALES AMOUNT ? 
SELECT DISTINCT MONTH_ID 
FROM sales_table 
WHERE YEAR_ID = 2005 ; -- THEY OPRATED JUST FIVE MONTHS IN THE YEAR 2005 

-- 3. THE SALES AMOUNT BY DEALSIZE 
SELECT DEALSIZE,ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
GROUP BY DEALSIZE
ORDER BY 2 DESC;

-- THE SALES AMOUNT BY COUNTRY 
SELECT COUNTRY,ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
GROUP BY COUNTRY
ORDER BY 2 DESC;

-- 5. THE SALES AMOUNT BY TERRITORY
SELECT TERRITORY,ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
GROUP BY TERRITORY
ORDER BY 2 DESC;

-- WHAT WAS THE BEST MONTH FOR SALES IN A SPECIFIC YEAR AND THE TOTAL ORDER ?
SELECT MONTH_ID,COUNT(ORDERLINENUMBER) ORDER_FREQUENCY, ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
WHERE YEAR_ID = 2004 
GROUP BY MONTH_ID
ORDER BY 3 DESC;

-- NOVEMBER HAS THE GRETEAST SALES OVER THE 2003 AND 2004
-- WHAT ARE THE BEST SELLING PRODUCT IN NOVEMBER 
SELECT PRODUCTLINE,COUNT(ORDERLINENUMBER) ORDER_FREQUENCY, ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
WHERE YEAR_ID = 2003 AND MONTH_ID = 11 
GROUP BY PRODUCTLINE
ORDER BY 3 DESC;

SELECT PRODUCTLINE,COUNT(ORDERLINENUMBER) ORDER_FREQUENCY, ROUND(SUM(SALES),2) TOTAL_REVENUE 
FROM sales_table 
WHERE YEAR_ID = 2004 AND MONTH_ID = 11 
GROUP BY PRODUCTLINE
ORDER BY 3 DESC;

-- 6. WHO ARE THE BEST CUSTOMERS ?
DROP TABLE IF EXISTS #RFM -- CREATE A TEMP TABLE TO STOCK THE CTEs
;WITH RFM AS 
(
	SELECT 
		CUSTOMERNAME,
		MAX(ORDERDATE) LAST_ORDER_DATE,
		(SELECT MAX(ORDERDATE) FROM sales_table)  MAX_ORDER_DATE,
		DATEDIFF(DD,MAX(ORDERDATE),(SELECT MAX(ORDERDATE) FROM sales_table)) RECENCY,
		COUNT(ORDERNUMBER) FREQUENCY,
		ROUND(SUM(sales),2) MONETORY
	FROM sales_table 
	GROUP BY CUSTOMERNAME
),
RFM_GROUP AS
(
	SELECT R.*,
		NTILE(4) OVER(ORDER BY RECENCY DESC) RECENCY_GROUP,
		NTILE(4) OVER(ORDER BY FREQUENCY) FREQUENCY_GROUP,
		NTILE(4) OVER(ORDER BY MONETORY) MONETARY_GROUP
	FROM RFM R
)
SELECT 
	RG.*,
	(RG.RECENCY_GROUP + RG.FREQUENCY_GROUP + RG.MONETARY_GROUP) COMBINE_SCORE,
	CAST (RG.RECENCY_GROUP AS VARCHAR) + CAST(RG.FREQUENCY_GROUP AS VARCHAR)
	+ CAST(RG.MONETARY_GROUP AS VARCHAR) SCORE
INTO #FRM -- CREATE A TEMP TABLE TO STOCK THE CTEs
FROM RFM_GROUP RG; 

SELECT 
CUSTOMERNAME, RECENCY_GROUP R_SCORE, FREQUENCY_GROUP F_SCORE, MONETARY_GROUP M_SCORE,
(CASE 
	WHEN SCORE IN (111, 112, 121, 123, 132, 211, 212, 114, 141) THEN 'LOST CUSTOMERS'
	WHEN SCORE IN (133, 134, 143, 244, 334, 343, 344) THEN 'SLIPPING AWAY CUSTOMERS'
	-- BIG SPENDER WHO HAVEN'T PURCHASED LATELY
	WHEN SCORE IN (311, 411, 331) THEN 'NEW CUSTOMERS'
	WHEN SCORE IN (222, 223, 233, 322) THEN 'POTENTIAL CHURNER CUSTOMERS'
	WHEN SCORE IN (323, 333, 321, 422, 332, 432) THEN 'ACTIVE CUSTOMERS'
	WHEN SCORE IN (433, 434, 443, 444) THEN 'LOYAL CUSTOMERS'
END) SEGMENT
FROM #FRM ;  

SELECT COUNT(DISTINCT CUSTOMERNAME)
FROM sales_table; -- VERY LOW CUSTOMER BASE( 92 CUSTOMERS) 